spring.application.name=salesforce_integration_service

# OAuth
salesforce.client-id=${SALESFORCE_CLIENT_ID}
salesforce.client-secret=${SALESFORCE_CLIENT_SECRET}

salesforce.username=${SALESFORCE_USERNAME}
salesforce.password=${SALESFORCE_PASSWORD}

# Salesforce
salesforce.base-url=${SALESFORCE_BASE_URL}

# Apex REST endpoint
salesforce.apex-endpoint=/services/apexrest/name-splitter/

# Camel
camel.springboot.main-run-controller=true

# Swagger
# Keep enabled for local testing
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info