apiVersion: v1
kind: Secret
metadata:
  name: salesforce-integration-secret
  namespace: salesforce-integration
type: Opaque
stringData:
  SALESFORCE_CLIENT_ID: "<your-client-id>"
  SALESFORCE_CLIENT_SECRET: "<your-client-secret>"