name: build-and-test

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and test
        run: mvn -B clean verify

      - name: Download OpenTelemetry Java Agent
        run: |
          curl -L \
            -o opentelemetry-javaagent.jar \
            https://repo1.maven.org/maven2/io/opentelemetry/javaagent/opentelemetry-javaagent/2.31.1/opentelemetry-javaagent-2.31.1.jar

      - name: Verify OpenTelemetry Java Agent
        run: ls -lh opentelemetry-javaagent.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::608744602923:role/github-actions-ecr-role
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t 608744602923.dkr.ecr.eu-north-1.amazonaws.com/salesforce-integration-service:${{ github.sha }} \
            .

      - name: Push Docker image to ECR
        run: |
          docker push \
            608744602923.dkr.ecr.eu-north-1.amazonaws.com/salesforce-integration-service:${{ github.sha }}